apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-calculator
  labels:
    app: simple-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-calculator
  template:
    metadata:
      labels:
        app: simple-calculator
    spec:
      containers:
        - name: simple-calculator
          image: docker.io/yourdockerhub/simple-calculator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
