apiVersion: v1
kind: Service
metadata:
  name: simple-calculator-service
spec:
  type: NodePort
  selector:
    app: simple-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007   # optional, Kubernetes can auto assign
